CREATE TABLE Surfer (
mail VARCHAR(40) NOT NULL PRIMARY KEY,
pseudo VARCHAR(30) NOT NULL,
name VARCHAR(30) NOT NULL,
firstname VARCHAR(30) NOT NULL,
passwrd VARCHAR(30) NOT NULL
);

CREATE TABLE Artist(
mail VARCHAR(40) NOT NULL PRIMARY KEY REFERENCES Surfer(mail),
description TEXT
);

CREATE TABLE Investor(
mail VARCHAR(40) NOT NULL PRIMARY KEY REFERENCES Surfer(mail),
address VARCHAR(200) NOT NULL
);